### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by akul-ka** [joeytwiddle/mongoose-generate-unique-key#2]
It seems to be 
`userSchema.plugin(generateUniqueKey('userKey', () => String(Math.floor(Math.random() * 1000000))));` instead of 
`userSchema.plugin('userKey', generateUniqueKey(() => String(Math.floor(Math.random() * 1000000))));`.
Custom field name has to be as parameter of `generateUniqueKey` function.

**Comment by joeytwiddle** [comment]
You are right!

Fixed in 53b3c9b. Thank you.
